// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5U-72RY-9nP1Cdz8Empp5Mvze-IXCBh0',
    appId: '1:705426421853:web:1d646e2d992e61283e35b4',
    messagingSenderId: '705426421853',
    projectId: 'tadolive',
    authDomain: 'tadolive.firebaseapp.com',
    storageBucket: 'tadolive.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf4Kd2WfiBDdzVdvAOSq90FO789lAnjgc',
    appId: '1:600034986475:android:642ace56647e2e5e5c71ae',
    messagingSenderId: '600034986475',
    projectId: 'meetlive-24239',
    storageBucket: 'meetlive-24239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8YuS56JJACBHAuz8zmusWZUYcZmnKRLU',
    appId: '1:600034986475:ios:1a6d25faa01100415c71ae',
    messagingSenderId: '600034986475',
    projectId: 'meetlive-24239',
    storageBucket: 'meetlive-24239.firebasestorage.app',
    iosBundleId: 'com.meetliveappspro.meetlivepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL08oG5pfKdbnOqOFBwGWDwSYbpBrxlXc',
    appId: '1:705426421853:ios:5b8135135f1a43763e35b4',
    messagingSenderId: '705426421853',
    projectId: 'tadolive',
    storageBucket: 'tadolive.firebasestorage.app',
    androidClientId: '705426421853-m1ccrq0sbfvevjer6mmie6ie0pd08oea.apps.googleusercontent.com',
    iosClientId: '705426421853-3ojp1kel9csighh21ic1cnbumvr3lgq2.apps.googleusercontent.com',
    iosBundleId: 'com.sheikhit.tadolive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5U-72RY-9nP1Cdz8Empp5Mvze-IXCBh0',
    appId: '1:705426421853:web:050b63e1cc70271e3e35b4',
    messagingSenderId: '705426421853',
    projectId: 'tadolive',
    authDomain: 'tadolive.firebaseapp.com',
    storageBucket: 'tadolive.firebasestorage.app',
  );

}